.TH "krillta" "1" "NLnet Labs"
.SH NAME
krillta - Krill Offline Trust Anchor
.SH SYNOPSIS
krillta [SUBCOMMAND]

krillta help [SUBCOMMAND]

krillta -h, --help

krillta -V, --version
.SH DESCRIPTION
The krillta tool is used for managing a Krill based RPKI Trust Anchor.

For more information visit https://krill.docs.nlnetlabs.nl/en/latest/trust-anchor.html

.SH SEE ALSO
krill(1)
