[package]
name = "krilltest"
version = "0.1.0"
description = "End-to-end testing for Krill"
authors.workspace = true
edition.workspace = true 
rust-version.workspace = true 
license.workspace = true 

[dependencies]
bytes    = "1"
clap     = { version = "*", features = ["cargo", "derive"]}
hex      = "0.4.3"
indoc    = "2.0.7"
krill    = { path = ".." }
nix      = { version = "*", features = ["signal"] }
rand     = "0.10.2"
rcgen    = "0.14"
reqwest  = { version = "*", features = ["blocking"] }
rpki     = "0.19.3"
tempfile = "*"

