#!/bin/bash -e
# Script based on the RPM %systemd_post scriptlet. See:
#   - https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_systemd
#   - https://cgit.freedesktop.org/systemd/systemd/tree/src/core/macros.systemd.in

K_USER=krill
K_GROUP=${K_USER}
K_HOME_DIR=/var/lib/krill
K_HOME_DIR_PERMS=700
K_CONF="/etc/krill.conf"

if [ $EUID -ne 0 ]; then
    echo >&2 "ERROR: RTRTR postinst script must be run as root"
    exit 1
fi

create_user() {
    # According to the CentOS 7 useradd man page:
    # --user-group causes a group by the same name as the user to be created
    # --create-home should force creation of a home dir even for a system account.
    useradd --system --home-dir ${K_HOME_DIR} --system --create-home --user-group ${K_USER}

    # Ensure that the home directory has the correct ownership
    chown -R ${K_USER}:${K_GROUP} ${K_HOME_DIR}

    # Ensure that the home directory has the correct permissions
    chmod ${K_HOME_DIR_PERMS} ${K_HOME_DIR}
}

init_systemd_service() {
    systemctl preset krill.service 2>&1 || :
}

generate_password() {
    # Tries not to depend on too many other commmands
    # being installed.
    date | md5sum | awk '{print $1}'
}

create_first_time_configuration() {
    if [ ! -f "${K_CONF}" ]; then
        # generate a token for authenticating with Krill
        ADMIN_TOKEN="$(generate_password)"

        # generate a config file using our preferred filesystem locations
        # and generated admin token
        # note: we don't configure Krill to store its PID file under /var/run/
        # because that requires root privileges potentially at least once per
        # boot, and Krill doesn't drop privileges yet so when run as a non-root
        # user has no right to create the file or missing /var/run/subdir.
        # See: https://stackoverflow.com/a/28312577
        krillc config simple \
            --data "${KRILL_DATA}" \
            --token "${ADMIN_TOKEN}" |
            sed -e "s|^\(### log_type.\+\)|\1\nlog_type = \"syslog\"|" \
                > "${KRILL_CONF}"
    fi
}

if [ $1 -eq 1 ] ; then
    # Initial installation
    create_user
    init_systemd_service
    create_first_time_configuration
fi