#!/bin/sh
set -e

KRILL_CONF="/etc/krill.conf"

case "$1" in
purge)
    # Per https://www.debian.org/doc/debian-policy/ch-files.html#behavior
    # "configuration files must be preserved when the package is removed, and
    #  only deleted when the package is purged."
    if [ -f ${KRILL_CONF} ]; then
        rm ${KRILL_CONF}
    fi
    ;;
esac