#!/bin/sh -e

KRILL_CONF="/etc/krill.conf"
KRILL_HOME="/var/lib/krill/"
KRILL_DATA="${KRILL_HOME}data/"
KRILL_USER="krill"

create_user() {
    if id ${KRILL_USER} > /dev/null 2>&1; then return; fi
    adduser --system --home "${KRILL_HOME}" --group ${KRILL_USER}
}

generate_password() {
    # Tries not to depend on too many other commmands
    # being installed.
    date | md5sum | awk '{print $1}'
}

create_first_time_configuration() {
    if [ ! -f "${KRILL_CONF}" ]; then
        # generate a token for authenticating with Krill
        GENERATED_TOKEN="$(generate_password)"

        # generate a config file using our preferred filesystem locations
        # and generated token
        # note: we don't configure Krill to store its PID file under /var/run/
        # because that requires root privileges potentially at least once per
        # boot, and Krill doesn't drop privileges yet so when run as a non-root
        # user has no right to create the file or missing /var/run/subdir.
        # See: https://stackoverflow.com/a/28312577
        krillc config simple \
            --data "${KRILL_DATA}" \
            --token "${GENERATED_TOKEN}" |
            sed -e "s|^\(### log_type.\+\)|\1\nlog_type = \"syslog\"|" \
                > "${KRILL_CONF}"
    fi
}

# See: https://salsa.debian.org/debian/debhelper/-/blob/debian/13.1/autoscripts/postinst-systemd-dont-enable
# This is what dh_installsystemd would add but Cargo Deb doesn't use debhelper
# so we have to add it ourselves manually.
manage_systemd() {
    if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
        if deb-systemd-helper debian-installed 'krill.service'; then
            # This will only remove masks created by d-s-h on package removal.
            deb-systemd-helper unmask 'krill.service' >/dev/null || true
    
            if deb-systemd-helper --quiet was-enabled 'krill.service'; then
                # Create new symlinks, if any.
                deb-systemd-helper enable 'krill.service' >/dev/null || true
            fi
        fi
    
        # Update the statefile to add new symlinks (if any), which need to be cleaned
        # up on purge. Also remove old symlinks.
        deb-systemd-helper update-state 'krill.service' >/dev/null || true
    fi
}

case "$1" in
configure)
    create_user
    create_first_time_configuration
    ;;
esac

manage_systemd $1
