#!/bin/sh -e
# See: https://salsa.debian.org/debian/debhelper/-/blob/debian/13.1/autoscripts/prerm-systemd
# This is what dh_installsystemd would add but Cargo Deb doesn't use debhelper
# so we have to add it ourselves manually.
manage_systemd() {
    if [ -d /run/systemd/system ]; then
        deb-systemd-invoke stop 'krill.service' >/dev/null || true
    fi
}

manage_systemd $1
