name: Packaging

on:
  push:
    tags:
      - v*

  # Allow triggering manually.
  workflow_dispatch:

jobs:
  package:
    # See: https://github.com/NLnetLabs/ploutos
    uses: NLnetLabs/ploutos/.github/workflows/pkg-rust.yml@v7
    secrets:
      DOCKER_HUB_ID: ${{ secrets.DOCKER_HUB_ID }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
    with:
      cross_build_args: --features static-openssl
      cross_max_wait_mins: 20
  
      docker_org: nlnetlabs
      docker_repo: krill
      docker_build_rules: pkg/rules/docker-images-to-build.yml
      docker_sanity_check_command: krillc --version

      package_build_rules: pkg/rules/packages-to-build.yml
      package_test_rules: pkg/rules/packages-to-test.yml
      package_test_scripts_path: pkg/test-scripts/test-<package>.sh

      deb_extra_build_packages: libssl-dev
      rpm_extra_build_packages: make openssl-devel perl-core
      rpm_scriptlets_path: pkg/rpm/scriptlets.toml

