name: Packaging

on:
  push:
    branches:
      - main
    tags:
      - v*

  # Triggering on PRs and arbitrary branch pushes is not enabled because most of the time only the CI build should be
  # triggered, not the packaging build. In cases where you want to test changes to this workflow this trigger enables
  # you to manually invoke this workflow on an arbitrary branch as needed.
  workflow_dispatch:

jobs:
  package:
    uses: NLnetLabs/ploutos/.github/workflows/pkg-rust.yml@v1
    secrets:
      DOCKER_HUB_ID: ${{ secrets.DOCKER_HUB_ID }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
    with:
      docker_org: nlnetlabs
      docker_repo: krill

      cross_build_rules_path: pkg/rules/cross-targets.yml
      docker_build_rules_path: pkg/rules/docker-images-to-build.yml
      package_build_rules_path: pkg/rules/packages-to-build.yml
      package_test_rules_path: pkg/rules/packages-to-test.yml
      package_test_scripts_path: pkg/test-scripts/test-<package>.sh

      cross_build_args: --features static-openssl
      deb_extra_build_packages: libssl-dev
      deb_maintainer: The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>
      docker_sanity_check_command: krillc --version
      rpm_extra_build_packages: openssl-devel
      rpm_scriptlets_path: pkg/rpm/scriptlets.toml

